version: '3.3'

services:
  data-plotter:
    image: foxy-trial
    volumes:
      - datasets:/home/anil-kumarchavali/foxy/datasets 
      - src:/home/anil-kumarchavali/foxy/parsing
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.dockers3f4lvpn.xauth:/tmp/.dockers3f4lvpn.xauth
      - /etc/localtime:/etc/localtime:ro 

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.dockers3f4lvpn.xauth
      - TERM=$TERM
    privileged: true
    network_mode: host
    command: rviz2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  datasets:
  src:
