version: '3.3'

services:
  data-plotter:
    image: foxy-trial
    volumes:
      - datasets:/home/anil-kumarchavali/foxy/datasets 
      - src:/home/anil-kumarchavali/foxy/parsing
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1001/gdm/Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro 

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - COOKIE=$COOKIE
      - TERM=$TERM
    privileged: true
    network_mode: host
    command: /bin/bash -c "rviz2"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  datasets:
  src:
