version: '3.3'

services:
  browser:
    image: fire-trial 
    volumes:
      - datasets:/home/anil-kumarchavali/foxy/datasets 
      - src:/home/anil-kumarchavali/foxy/parsing
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - COOKIE=${COOKIE}
    network_mode: host
    command: /bin/bash -c "xauth add $COOKIE && firefox"

volumes:
  datasets:
  src:
